use wrfcenter;
CREATE TABLE WRFCENTER_INVENTORY_ITEM (
  INVENTORY_ITEM_ID int(11) NOT NULL,
  R_INVENTORY_ITEM_ID int(11)  NOT NULL,
  QUANTITY int(11)  DEFAULT 0,
  CREATED_BY varchar(255) NOT NULL,
  CREATED_DATETIME DATETIME NOT NULL,
  LAST_MODIFIED_BY varchar(255) NOT NULL,
  LAST_MODIFIED_DATETIME DATETIME NOT NULL,
  IS_ACTIVE tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE WRFCENTER_INVENTORY_AUDIT (
  INVENTORY_AUDIT_ID int(11) NOT NULL,
  INVENTORY_ITEM_ID int(11)  NOT NULL,
  QUANTITY int(11) DEFAULT 0,
  SUNSET tinyint(1) DEFAULT 0,
  CREATED_BY varchar(255) NOT NULL,
  CREATED_DATETIME DATETIME NOT NULL,
  LAST_MODIFIED_BY varchar(255) NOT NULL,
  LAST_MODIFIED_DATETIME DATETIME NOT NULL,
  IS_ACTIVE tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE WRFCENTER_INVENTORY_ITEM
  ADD PRIMARY KEY (INVENTORY_ITEM_ID);

ALTER TABLE WRFCENTER_INVENTORY_ITEM
  MODIFY INVENTORY_ITEM_ID int(11) NOT NULL AUTO_INCREMENT,
  ADD KEY FK_invItem_invItemRID (R_INVENTORY_ITEM_ID);

ALTER TABLE WRFCENTER_INVENTORY_ITEM
  ADD CONSTRAINT FK_invItem_invItemRID FOREIGN KEY (R_INVENTORY_ITEM_ID) REFERENCES WRFCENTER_R_DATA (ID);

ALTER TABLE WRFCENTER_INVENTORY_AUDIT
  ADD PRIMARY KEY (INVENTORY_AUDIT_ID);

ALTER TABLE WRFCENTER_INVENTORY_AUDIT
  MODIFY INVENTORY_AUDIT_ID int(11) NOT NULL AUTO_INCREMENT,
  ADD KEY FK_invAudit_invAuditItemID (INVENTORY_ITEM_ID);

ALTER TABLE WRFCENTER_INVENTORY_AUDIT
  ADD CONSTRAINT FK_invAudit_invAuditItemID FOREIGN KEY (INVENTORY_ITEM_ID) REFERENCES WRFCENTER_INVENTORY_ITEM (INVENTORY_ITEM_ID);